### ISSUE TITLE
stdout of wkhtmltopdf will be added to pdf

### ISSUE THREAD

**Issue by harald-k** [jhonnymertz/java-wkhtmltopdf-wrapper#19] opened 2017-03-21 15:02 UTC
When running the following code on Linux, the standard output of wkhtmltopdf will be added to the created pdf. Without xvfb on Windows the created pdf is as expected.

Linux environment:
Ubuntu 14.04.3 LTS
wkhtmltopdf 0.12.2.1 (with patched qt)

Windows environment:
Windows 10
wkhtmltopdf 0.12.4 (with patched qt)

```java
final XvfbConfig xc = new XvfbConfig();
xc.addParams(new Param("--auto-servernum"));

final WrapperConfig wc = new WrapperConfig();
wc.setXvfbConfig(xc);

Pdf pdf = new Pdf(wc);

pdf.addPage("http://...", PageType.url);

pdf.addParam(new Param("--orientation", "landscape"));

Files.copy(new ByteArrayInputStream(pdf.getPDF()), outputFile);
```

Created PDF
```
Loading pages (1/6)
[>                                                           ] 0%
[======>                                                     ] 10%
[=======>                                                    ] 12%
[==========>                                                 ] 17%
[=============>                                              ] 22%
[===============>                                            ] 25%
[================>                                           ] 27%
[=======================>                                    ] 39%
[=========================>                                  ] 42%
[==========================>                                 ] 44%
[============================>                               ] 47%
[=============================>                              ] 49%
[==============================>                             ] 50%
[==============================>                             ] 50%
[==============================================>             ] 78%
[=================================================>          ] 83%
[===================================================>        ] 86%
[============================================================] 100%
Counting pages (2/6)                                               
[============================================================] Object 1 of 1
Resolving links (4/6)                                                       
[============================================================] Object 1 of 1
Loading headers and footers (5/6)                                           
Printing pages (6/6)
[>                                                           ] Preparing
[>                                                           ] Page 1 of 60
%PDF-1.4
1 0 obj
<<
[...]
```

**Comment by stepan-sadovnykov** [comment] 2017-05-17 10:09
It is possible to use
`pdf.addParam(new Param("-q"));`
as a workaround, this parameter hides most of wkhtmltopdf messages. 
In my case without this some PDFs produced were unreadable.

**Comment by jhonnymertz** [comment] 2017-05-23 14:35
Sorry for the late reply.
So, I was not able to reproduce the bug. The code works for me on the described Linux environment. It is hard to say where the bug is happening though. It can be in the wrapper streams or in the wkhtmltopdf itself.

Please, can you check if the command generated by the wrapper can be properly used on the command line? You can use the method `getCommand()` on the class `Pdf`.

**Comment by kalle77** [comment] 2017-07-04 22:53
I seem to be running into the exact same problem on:
Ubuntu 15.04 &
wkhtmltopdf 0.12.4 (with patched qt)

The command im running:
wkhtmltopdf --page-size A4 --header-html http://localhost:8080/digitaldocs/headerView.htm?userAccountId=39&projectId=31609 --footer-html http://localhost:8080/digitaldocs/footerView.htm?projectId=31609 --margin-top 27mm --margin-bottom 20mm --footer-spacing 3 --header-spacing 5 http://localhost:8080/digitaldocs/printView.htm?documentId=10 -

As Stepan wrote; the problem is mitigated by adding '-q'... The problem did not occur on OSX so maybe its an wkhtmltopdf problem (it seems like it has had similar bugs before which were supposed to be fixed).

BR,
Kalle

**Comment by emax19** [comment] 2018-10-03 14:04
I have the same problem

**Comment by rrsdev** [comment] 2019-03-13 15:45
I ended up creating a new class that I named Pdf2 and copied the code from the original Pdf class.  I added a property for "pdfFileOut" and then in the saveAs set that property.  In the build command I then check and if that property is set send it instead of the '-' to the wkhtmltopdf command; this saves the file directly and by-passes the stdout issues.  I initially looked into simply subclassing Pdf but some of the key methods are private so it didn't make that much sense to do that - if those methods were protected there would be more flexibility (alternatively a pluggable get command class).

**Comment by jhonnymertz** [comment] 2019-03-16 18:15
@rrsdev nice that you were able to solve and posted the solution you've adopted. Thanks! I'll try to fix it in future releases and improve the code to be more flexible. Anyway, pull requests are welcomed =)

**Comment by jhonnymertz** [comment] 2019-03-24 20:31
A pull request #53, created by @rrsdev (thanks!), was merged and now we have a method `saveAsDirect(String path)`, which executes wkhtmltopdf passing the `path` directly as output for wkhtmltopdf, instead of the standard input `-`. This saves the results directly to the specified file `path`. 

Please, check it out in the release 1.0.10-RELEASE. I've also created a `known issues` section in the README.md with an explanation regarding this. Maybe this fix does not solve the problem for everyone, because it demands the file to be saved into the file system, but it is a good start.

**Closed** 2020-03-14 21:21 UTC
Labels: bug
